@BaseUrl = https://localhost:7151
@Auth_Token = "e2uidueg"

GET {{BaseUrl}}/contact
Authorization: {{Auth_Token}}
###
GET {{BaseUrl}}/contact/4

###
DELETE {{BaseUrl}}/contact/4

###
POST {{BaseUrl}}/contact
Content-Type: application/json

{
  "name": "string",
  "email": "string",
  "phone": "string",
  "message": "string"
}
###
PUT {{BaseUrl}}/contact/4
Content-Type: application/json

{
  "name": "Pramod",
  "email": "string",
  "phone": "string",
  "message": "string"
}



